# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts

version: 2.1

orbs:
  # Note: We are using the latest version of hello-build, whereas module B uses an older one
  module-build-aws-html-site-hello-build: circleci/hello-build@0.0.14

jobs:
  module-build-aws-html-site-build:
    docker:
      - image: cimg/base:stable
    steps:
      - common-say-hello:
          to: module-build-aws-html-site
      - run: echo 'Hello build-aws-html-site again!'

workflows:
  module-build-aws-html-site-workflow:
    jobs:
      - common-pre
      - module-build-aws-html-site-build:
          requires:
            - common-pre
      - module-build-aws-html-site-hello-build/hello-build:
          requires:
            - common-pre
